### ISSUE TITLE
SMS notification is not working.

### ISSUE THREAD

**Issue by landtax** [taverna/taverna-server#1]
Hi,

i've been (and i am actually) trying to configure SMS dispatcher to send a post message to url. The idea is that we are developing a website that sends workflows to taverna server and we'd like taverna server notifies the finished status to our website.

I thought that using SMS dispatcher would make the job but it is not working as expected.

There is a first problem with the configuration.

bean.xml is not configuring all the properties as it should. Is not configuring service (so cannot change the default uri for sending the post message).

Also, SMSDispatcher is not getting the data from tavernaserver.properties properly since it is using a function valid() that discards the value if it starts with ${

The steps i did is to change bean.xml, add service and replace ${} with the real value

``` xml
<bean id="dispatch.sms" class="org.taverna.server.master.notification.SMSDispatcher">
<property name="usernameField" value="username" />
<property name="passwordField" value="password" />
<property name="destinationField" value="to" />
<property name="messageField" value="text" />
<property name="cooldownSeconds" value="1" />
<property name="service" value="http://localhost" />
</bean>
```

but it is not workign. Well it gets initialized (it is listed in /rest/policy/enabledNotificationFabrics) but is not doing the post to localhost. So, something is still not working.

I'm on version 2.4.1 I dont know if it is already fixed in newer versions. I'm not a java developer and I don't see easily how to fork, compile etc to test it on my own.

Any help would be very appreciated. :(

Thanks in advance.

**Comment by dkfellows** [comment]
So, the bean is entering the enabled state but isn't working? Is anything written to the log that seems relevant (i.e., that comes from the bean)? The log will be in `catalina.out` by default (wherever that gets written to, which depends on your tomcat installation/configuration).

The replacement of `${sms.userfield}` with the value of the `sms.userfield` properties should be done by Spring (and it's a feature I use in quite a lot of other places) based on the content of the `/WEB-INF/tavernaserver.properties` file. IIRC, the literal `${sms.userfield}` only appears if the property is unset (which is why the code checks for it).

The properties you should set, at least when testing, are:
- `sms.service` — the URL of the gateway service (e.g., `http://localhost:8080/test_sms_servlet/`)
- `sms.user` — account name to submit with (sent to service via `username` HTTP POST field)
- `sms.pass` — password for account (sent to service via `password` HTTP POST field)

As far as APIs go, it's not very nice! But it was clear enough for me to code.

(In reality, I actually recommend using the Atom feed instead of SMS notifications...)

**Comment by dkfellows** [comment]
(Also, our official issue database is at http://dev.mygrid.org.uk/issues/browse/TAVSERV)

**Comment by landtax** [comment]
Thanks a lot for your response it was very clear. :) I wanted to post it in your official issue tracker but i have not got access. :(

In catalina.log does not print anything relevant. Well, it does not complain (ever) about sms configurartion even when it should! 

This extract from SMSDispatcher should print to catalina.log if sms.service is configured in tavernaserver.properties but it is null. And it does not complain ever. That's how i found that setService was never called and I decided to not use `tavernaserver.properties`

``` java
    public void setService(String serviceURL) {
        String s = valid(serviceURL, "");
        if (s.isEmpty()) {
            log.warn("did not get sms.service from servlet config; using default ("
                    + DEFAULT_SMS_GATEWAY + ")");
            s = DEFAULT_SMS_GATEWAY;
        }
        try {
            service = new URI(s);
        } catch (URISyntaxException e) {
            service = null;
        }
    }
```

Also in bean.xml properties `service`, `user` and `password` are not set.

``` java
    <bean id="dispatch.sms" class="org.taverna.server.master.notification.SMSDispatcher">
        <property name="usernameField" value="${sms.userfield}" />
        <property name="passwordField" value="${sms.passfield}" />
        <property name="destinationField" value="${sms.destfield}" />
        <property name="messageField" value="${sms.msgfield}" />
        <property name="cooldownSeconds" value="${message.cooldown}" />
    </bean>
```

In the other hand, when i write the "missing" properties in beans.xml 

``` xml
   <bean id="dispatch.sms" class="org.taverna.server.master.notification.SMSDispatcher">
     <property name="usernameField" value="username" />
     <property name="passwordField" value="password" />
     <property name="destinationField" value="to" />
     <property name="messageField" value="text" />
     <property name="cooldownSeconds" value="1" />
     <property name="user" value="user" />
     <property name="password" value="pass" />
     <property name="service" value="" />
   </bean>
```

It prints to the log!! As it should. setService is called!!

```
20130321T143902.179 WARN  Notification SMSDispatcher - did not get sms.service from servlet config; using default (https://www.intellisoftware.co.uk/smsgateway/sendmsg.aspx)
```

Finally, when i setup the service to my localhost

``` xml
   <bean id="dispatch.sms" class="org.taverna.server.master.notification.SMSDispatcher">
     <property name="usernameField" value="username" />
     <property name="passwordField" value="password" />
     <property name="destinationField" value="to" />
     <property name="messageField" value="text" />
     <property name="cooldownSeconds" value="1" />
     <property name="user" value="user" />
     <property name="password" value="pass" />
     <property name="service" value="http://localhost" />
   </bean>
```

there is no line log about sms wrong configuration. I can assume that setService was called and configured with `http://localhost`

But it does not work. :( I run a workflow, it gets printed in the log that the process was done. 

```
20130321T144643.318 INFO  forker StdOut - Subprocess(out):security dir location: /home/taverna/.taverna-server-security/c6e3233c-ff5c-4054-9088-40da0c3f1049
20130321T144643.319 INFO  forker StdOut - Subprocess(out):password of length 6 will be written to subprocess stdin
20130321T144643.348 INFO  forker StdOut - Subprocess(out):starting [/bin/sh, /var/lib/tomcat6/webapps/taverna-server/WEB-INF/classes/util/taverna-commandline-2.4.0/executeworkflow.sh, -logfile, /tmp/c6e3233c-ff5c-4054-9088-40da0c3f1049/logs/detail.log, -cmdir, /home/taverna/.taverna-server-security/c6e3233c-ff5c-4054-9088-40da0c3f1049, -cmpassword, -inputfile, input_urls, /tmp/c6e3233c-ff5c-4054-9088-40da0c3f1049/input1.txt, -inputvalue, language, es, -outputdir, /tmp/c6e3233c-ff5c-4054-9088-40da0c3f1049/out, /tmp/taverna6365171722958236962.t2flow] in directory /tmp/c6e3233c-ff5c-4054-9088-40da0c3f1049
```

and the `/admin/usageRecords`

``` xml
<ns3:usageRecord><ns2:RecordIdentity ns2:createTime="2013-03-21T14:47:05.269+01:00" ns2:recordId="011069fd-a750-4234-ab5b-0a2233d20a29"/><ns2:UserIdentity><ns2:LocalUserId>taverna</ns2:LocalUserId></ns2:UserIdentity><ns2:JobName>c6e3233c-ff5c-4054-9088-40da0c3f1049</ns2:JobName><ns2:Status>Completed</ns2:Status><ns2:StartTime>2013-03-21T14:46:43.342+01:00</ns2:StartTime><ns2:EndTime>2013-03-21T14:47:05.268+01:00</ns2:EndTime><ns2:WallDuration>P0Y0M0DT0H0M21.926S</ns2:WallDuration><ns2:Host>landtax-desktop</ns2:Host></ns3:usageRecord></ns3:usageRecordList>
```

but the http post request to localhost was not done. And I cannot trace it without debugging. I need your help :(

I don't like the idea of atom feed. I'd need a process polling every X seconds for the atom url. Does not make sense to me to have another server/process polling.  A POST to a url with the ID of the job would be enough to update the status in my web application.

I'm sorry to cause problems but would be great to have taverna server working in our institute and connected to our webapps. :)

Thanks a lot :)
