### ISSUE TITLE
Empty feed when it shouldn't

### ISSUE THREAD

**Issue by landtax** [taverna/taverna-server#3]
Hi again :)

I'm using the feed to get notifications about finished jobs. I just found out that if you restart taverna server and fetch the feed url, it is empty. It is needed to create at least one job after the restart in order to get the populated feed.

It is breaking completely our workflow since servers get restarted "often" and feed fetchers do not get the updated info until somebody starts a new job.

Does it make sense?

**Comment by dkfellows** [comment]
That sounds like a bug. I don't know what's going wrong at the moment — the feed _should_ just pull its information direct from the database without regard for whether anything's been inserted this session — but it certainly sounds like it isn't right yet.

(Just to check: which exact version are you using?)

**Comment by landtax** [comment]
Hi!! 

version 2.4.1

**Comment by dkfellows** [comment]
The feed was thoroughly wrong before; it's been completely reworked in 2.5, and you should check out the 2.5.4 release. There's a [release candidate build](http://build.mygrid.org.uk/ci/view/Taverna%20Server/job/taverna-server-2.5-auto/263/uk.org.taverna.server$server-webapp/artifact/uk.org.taverna.server/server-webapp/2.5.4/server-webapp-2.5.4.war) you can test.

Warning though, that's not the final build (I'm just waiting for a check of how things are in one of our portal deployments) and that isn't a link that's guaranteed to persist (it's just to a particular build). If we're sufficiently satisfied, I'll push the tag and do a full release build.

**Comment by landtax** [comment]
Good news! We'll have a look! Thanks :)
