### ISSUE TITLE
Can't discover artifact for net.sf.taverna.t2.activities:jsonpath-activity

### ISSUE THREAD

**Issue by ultraman008** [taverna/taverna-server#8]
When a workflow with a jsonpath activity is run, server throws an error, which is visible in the workflow's detail.log:

> WARN 2016-07-20 17:58:32,316 (net.sf.taverna.t2.workflowmodel.serialization.xml.AbstractXMLDeserializer:167) - Can't discover artifact for net.sf.taverna.t2.activities:jsonpath-activity

**Comment by ianwdunlop** [comment]
I would hazard a guess that the jsonpath activity is not one of the default activities that the taverna server installation includes. Have you tried running the workflow in a stand alone desktop version of taverna? Does it include jsonpath? I would recommend asking this question on the taverna user or dev lists, see https://taverna.incubator.apache.org/community/lists.

**Comment by ultraman008** [comment]
Yes, this feature is included in the taverna workbench core 2.5.0. I'll try asking on the link you provided.
